audio:
  volume: 30  

notifications:
  fajr:
    enabled: true
    type: adhan

  dhuhr:
    enabled: false
    type: adhan

  asr:
    enabled: true
    type: adhan

  maghrib:
    enabled: false
    type: adhan

  isha:
    enabled: false
    type: adhan

  final_third:
    enabled: false
    type: adhan
